[package]
name = "block-entity-finder"
version = "0.1.1"
authors = ["Andreas Ots <qrpth@qrpth.eu>"]
description = "Tool to find chunks with the most block entities"
license = "Apache-2.0"

[dependencies]
byteorder = "1.0.0"
clap = "2.20.5"
hematite-nbt = "0.3.0"
